apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce  # One node can read/write at a time
  resources:
    requests:
      storage: 1Gi  # Same size as the PV
